# H2 Database Configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/bookdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # ?? create-drop (???), validate (???)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # Lazy Loading ?? ??